version: '3.9'

services:
  bff:
    build:
      context: bff
      dockerfile: Dockerfile
    container_name: bff
    environment:
      - BFF_ENCASHMENT_HOST=encashment
      - BFF_ALGO_HOST=algo
    ports:
      - $BFF_PORT:$BFF_PORT
  encashment:
    build:
      context: encashment
      dockerfile: Dockerfile
    container_name: encashment
    ports:
      - $ENCASHMENT_PORT:$ENCASHMENT_PORT
  algo:
    build:
      context: algo
      dockerfile: Dockerfile
    container_name: algo
    ports:
      - $ALGO_PORT:$ALGO_PORT