version: '3.9'

services:
  bff:
    build:
      context: bff
      dockerfile: Dockerfile
    container_name: bff
    ports:
      - 9001:9001
  encashment:
    build:
      context: encashment
      dockerfile: Dockerfile
    container_name: encashment
    ports:
      - 9002:9002
  algo:
    build:
      context: algo
      dockerfile: Dockerfile
    container_name: algo
    ports:
      - 9003:9003