version: '3.9'

services:
  bff:
    build:
      context: bff
      dockerfile: Dockerfile
    container_name: bff
    environment:
      - BFF_ATM_HOST=atm
      - BFF_ALGO_HOST=algo
    ports:
      - $BFF_PORT:$BFF_PORT
  atm:
    build:
      context: atm
      dockerfile: Dockerfile
    container_name: atm
    ports:
      - $ATM_PORT:$ATM_PORT
  algo:
    build:
      context: algo
      dockerfile: Dockerfile
    container_name: algo
    ports:
      - $ALGO_PORT:$ALGO_PORT
  front:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - $FRONT_PORT:$FRONT_PORT