name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest

      - name: Test atm
        run: pytest atm/tests

  docs:
    
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install lazydocs mkdocs mkdocs-awesome-pages-plugin
      - name: build docs
        run: chmod +x build-docs.sh && ./build-docs.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
